In [6]:
import pandas as pd

marcap_2022 = pd.read_csv('csv/2022_marcap.csv', encoding='CP949')
marcap_2022.drop(columns=['종가','대비','등락률','시가','고가','저가','거래량','거래대금','상장주식수'], inplace=True)
marcap_2022['시가총액'] = marcap_2022['시가총액'].sort_values(ascending=False)

marcap_2022

       종목코드       종목명          시가총액
0      5930      삼성전자  3.301290e+14
1    373220  LG에너지솔루션  1.019070e+14
2    207940  삼성바이오로직스  5.843390e+13
3       660    SK하이닉스  5.460020e+13
4     51910      LG화학  4.235540e+13
..      ...       ...           ...
938    2785    진흥기업우B  4.230371e+09
939    1525       동양우  3.947301e+09
940    1527     동양2우B  3.887969e+09
941    2787   진흥기업2우B  3.832504e+09
942     547   흥국화재2우B  2.488320e+09

[943 rows x 3 columns]

### S / B 구분

In [7]:
marcap_2022['기업구분'] = 'S'
marcap_2022

       종목코드       종목명          시가총액 기업구분
0      5930      삼성전자  3.301290e+14    S
1    373220  LG에너지솔루션  1.019070e+14    S
2    207940  삼성바이오로직스  5.843390e+13    S
3       660    SK하이닉스  5.460020e+13    S
4     51910      LG화학  4.235540e+13    S
..      ...       ...           ...  ...
938    2785    진흥기업우B  4.230371e+09    S
939    1525       동양우  3.947301e+09    S
940    1527     동양2우B  3.887969e+09    S
941    2787   진흥기업2우B  3.832504e+09    S
942     547   흥국화재2우B  2.488320e+09    S

[943 rows x 4 columns]

In [8]:
bigComp = marcap_2022.iloc[0:100, ]
bigComp['기업구분'] = 'B'
bigComp

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_92796/2538893657.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigComp['기업구분'] = 'B'

      종목코드       종목명          시가총액 기업구분
0     5930      삼성전자  3.301290e+14    B
1   373220  LG에너지솔루션  1.019070e+14    B
2   207940  삼성바이오로직스  5.843390e+13    B
3      660    SK하이닉스  5.460020e+13    B
4    51910      LG화학  4.235540e+13    B
..     ...       ...           ...  ...
95    5940    NH투자증권  2.908710e+12    B
96    3410     쌍용C&E  2.902230e+12    B
97  112610     씨에스윈드  2.901390e+12    B
98    2790      아모레G  2.877790e+12    B
99   16360      삼성증권  2.808490e+12    B

[100 rows x 4 columns]

In [9]:
smallComp = marcap_2022.iloc[100: , ]
smallComp

       종목코드       종목명          시가총액 기업구분
100   47050  포스코인터내셔널  2.788280e+12    S
101  139480       이마트  2.731830e+12    S
102    5387    현대차2우B  2.696270e+12    S
103   30000      제일기획  2.651700e+12    S
104    1450      현대해상  2.632830e+12    S
..      ...       ...           ...  ...
938    2785    진흥기업우B  4.230371e+09    S
939    1525       동양우  3.947301e+09    S
940    1527     동양2우B  3.887969e+09    S
941    2787   진흥기업2우B  3.832504e+09    S
942     547   흥국화재2우B  2.488320e+09    S

[843 rows x 4 columns]

In [10]:
comp = pd.concat([bigComp, smallComp], axis=0)
comp

       종목코드       종목명          시가총액 기업구분
0      5930      삼성전자  3.301290e+14    B
1    373220  LG에너지솔루션  1.019070e+14    B
2    207940  삼성바이오로직스  5.843390e+13    B
3       660    SK하이닉스  5.460020e+13    B
4     51910      LG화학  4.235540e+13    B
..      ...       ...           ...  ...
938    2785    진흥기업우B  4.230371e+09    S
939    1525       동양우  3.947301e+09    S
940    1527     동양2우B  3.887969e+09    S
941    2787   진흥기업2우B  3.832504e+09    S
942     547   흥국화재2우B  2.488320e+09    S

[943 rows x 4 columns]

### 1/pbr H / L 처리

In [11]:
pbr_2022 = pd.read_csv('csv/2022_pbr.csv', encoding='CP949')
pbr_2022.drop(columns=['종목코드','종가','대비','등락률','EPS','PER','선행 EPS','선행 PER','BPS','주당배당금','배당수익률'], inplace=True)
pbr_2022 = pbr_2022.sort_values(by=['PBR'], ascending=[True]).reset_index(drop=True)

pbr_2022['PBR'].fillna(0, inplace=True) # 결측치 0으로 처리


pbr_2022

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_92796/3919177697.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbr_2022['PBR'].fillna(0, inplace=True) # 결측치 0으로 처리

         종목명   PBR
0        HDC  0.13
1       세원정공  0.14
2       한신공영  0.15
3     롯데하이마트  0.16
4       태광산업  0.16
..       ...   ...
909   현대차3우B  0.00
910     현대차우  0.00
911    호텔신라우  0.00
912  흥국화재2우B  0.00
913    흥국화재우  0.00

[914 rows x 2 columns]

In [12]:
pbr_2022['1/PBR'] = pbr_2022['PBR'].apply(lambda x : 'H' if x < 1 else 'L')
# pbr_2022['1/PBR'].value_counts()
# pbr_2022[pbr_2022['1/PBR'] == 'L']
pbr_2022

         종목명   PBR 1/PBR
0        HDC  0.13     H
1       세원정공  0.14     H
2       한신공영  0.15     H
3     롯데하이마트  0.16     H
4       태광산업  0.16     H
..       ...   ...   ...
909   현대차3우B  0.00     H
910     현대차우  0.00     H
911    호텔신라우  0.00     H
912  흥국화재2우B  0.00     H
913    흥국화재우  0.00     H

[914 rows x 3 columns]

In [13]:
table = pd.merge(comp, pbr_2022, on='종목명')
table['1/PBR'].value_counts()

1/PBR
H    637
L    277
Name: count, dtype: int64

## 제조업 기업 기준 (기업구분, 1/PBR 병합)

In [14]:
menu = pd.read_csv('csv/리얼 배당성향.csv', encoding='CP949')
menu['회사명'] = menu['회사명'].str.lstrip('(주)')
menu['회사명'] = menu['회사명'].str.rstrip('(주)')
menu.drop(columns=['거래소코드','회계년도','배당성향'], inplace=True)
menu.columns=['종목명']
menu

manufacture = pd.merge(table, menu, on='종목명')
manufacture

       종목코드       종목명          시가총액 기업구분    PBR 1/PBR
0      5930      삼성전자  3.301290e+14    B   1.27     L
1    207940  삼성바이오로직스  5.843390e+13    B  11.01     L
2      6400     삼성SDI  4.063980e+13    B   2.69     L
3       270        기아  2.403800e+13    B   0.68     H
4     35720       카카오  2.365130e+13    B   2.31     L
..      ...       ...           ...  ...    ...   ...
538    1210      금호전기  2.534986e+10    S   0.60     H
539   25620   제이준코스메틱  2.321030e+10    S   0.38     H
540   71950       코아스  2.256226e+10    S   1.20     L
541    8500      일정실업  1.968000e+10    S   1.04     L
542   30790     비케이탑스  1.920832e+10    S   2.71     L

[543 rows x 6 columns]

In [451]:
manufacture.to_csv('manufacture.csv')

In [377]:
BL_pbr = manufacture.loc[(manufacture['기업구분'] == 'B') & (manufacture['1/PBR'] == 'L')]
BH_pbr = manufacture.loc[(manufacture['기업구분'] == 'B') & (manufacture['1/PBR'] == 'H')]
SL_pbr = manufacture.loc[(manufacture['기업구분'] == 'S') & (manufacture['1/PBR'] == 'L')]
SH_pbr = manufacture.loc[(manufacture['기업구분'] == 'S') & (manufacture['1/PBR'] == 'H')]

In [399]:
BL_pbr_rtn = pd.merge(BL_pbr, acc, on='종목명')
BL_pbr_rtn.dropna(axis=0, inplace=True)

BH_pbr_rtn = pd.merge(BH_pbr, acc, on='종목명')
BH_pbr_rtn.dropna(axis=0, inplace=True)

SL_pbr_rtn = pd.merge(SL_pbr, acc, on='종목명')
SL_pbr_rtn.dropna(axis=0, inplace=True)

SH_pbr_rtn = pd.merge(SH_pbr, acc, on='종목명')
SH_pbr_rtn.dropna(axis=0, inplace=True)

In [379]:
# BL_pbr_rtn[BL_pbr_rtn['Date'] == '2023-03-31']
BL_pbr_rtn

        종목코드    종목명          시가총액 기업구분   PBR 1/PBR  Close  sell_rtn       Date
1       5930   삼성전자  3.301290e+14    B  1.27     L  69300  0.002894 2022-04-04
2       5930   삼성전자  3.301290e+14    B  1.27     L  69200 -0.001443 2022-04-05
3       5930   삼성전자  3.301290e+14    B  1.27     L  68500 -0.010116 2022-04-06
4       5930   삼성전자  3.301290e+14    B  1.27     L  68000 -0.007299 2022-04-07
5       5930   삼성전자  3.301290e+14    B  1.27     L  67800 -0.002941 2022-04-08
...      ...    ...           ...  ...   ...   ...    ...       ...        ...
9243  112610  씨에스윈드  2.901390e+12    B  3.24     L  78400  0.000000 2023-05-24
9244  112610  씨에스윈드  2.901390e+12    B  3.24     L  78600  0.002551 2023-05-25
9245  112610  씨에스윈드  2.901390e+12    B  3.24     L  76100 -0.031807 2023-05-26
9246  112610  씨에스윈드  2.901390e+12    B  3.24     L  80400  0.056505 2023-05-30
9247  112610  씨에스윈드  2.901390e+12    B  3.24     L  79000 -0.017413 2023-05-31

[9216 rows x 9 columns]

In [380]:
import numpy as np

# def weighted_average(group, avg_name, weight_name):
def weighted_average(group, avg_name, _name):
    d = group[avg_name]
    # w = group[weight_name]
    w = group[_name]
    try:
        # return (d * w).sum() / w.sum()
        return d.sum() / w.nunique()
    except ZeroDivisionError:
        return np.nan

In [400]:
BH_pbr_avgRtn = BH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BH_pbr_avg'})
BL_pbr_avgRtn = BL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BL_pbr_avg'})
SH_pbr_avgRtn = SH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SH_pbr_avg'})
SL_pbr_avgRtn = SL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SL_pbr_avg'})

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_75707/3476675855.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  BH_pbr_avgRtn = BH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BH_pbr_avg'})
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_75707/3476675855.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  BL_pbr_avgRtn = BL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BL_pbr_avg'})
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_75707/3476675855.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  SH_pbr_avgRtn = SH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SH_pbr_avg'})
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_75707/3476675855.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  SL_pbr_avgRtn = SL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SL_pbr_avg'})

In [422]:
from functools import reduce

pbr_avgRtn_list = [BH_pbr_avgRtn, BL_pbr_avgRtn, SH_pbr_avgRtn, SL_pbr_avgRtn]
df_merge = reduce(lambda left, right: pd.merge(left, right, on='Date'), pbr_avgRtn_list)
# pd.merge([BH_pbr_avgRtn, BL_pbr_avgRtn, SH_pbr_avgRtn, SL_pbr_avgRtn], on='Date',axis=1)
df_merge

          Date  BH_pbr_avg  BL_pbr_avg  SH_pbr_avg  SL_pbr_avg
0   2023-04-04    0.006634    0.015729    0.010173    0.009385
1   2023-04-05   -0.002874    0.005084   -0.000961    0.004973
2   2023-04-06   -0.009685   -0.008185   -0.008797   -0.006539
3   2023-04-07   -0.000917    0.000808    0.000233    0.002926
4   2023-04-10    0.004760    0.004393   -0.006439   -0.003749
..         ...         ...         ...         ...         ...
234 2024-03-19   -0.026583   -0.009621   -0.003006   -0.003027
235 2024-03-20    0.003264    0.007288    0.003992    0.008088
236 2024-03-21    0.019513    0.010174    0.008600    0.007848
237 2024-03-22   -0.004787    0.003787    0.002175    0.005545
238 2024-03-25   -0.008217    0.001042   -0.001873   -0.000865

[239 rows x 5 columns]

In [410]:
df_merge.iloc[[0]]['BH_pbr_avg']

0    0.006634
Name: BH_pbr_avg, dtype: float64

In [447]:
smb = []
hml = []
for i in df_merge.index :
    SMB = ((df_merge.loc[i]['SH_pbr_avg']) + (df_merge.loc[i]['SL_pbr_avg'])) - ((df_merge.loc[i]['BH_pbr_avg']) + (df_merge.loc[i]['BL_pbr_avg'])) / 2
    smb.append(SMB)
    HML = ((df_merge.loc[i]['SH_pbr_avg']) + (df_merge.loc[i]['BH_pbr_avg'])) - ((df_merge.loc[i]['SL_pbr_avg']) + (df_merge.loc[i]['BL_pbr_avg'])) / 2
    hml.append(HML)

df_merge['SMB'] = smb
df_merge['HML'] = hml

df_merge

,Date,BH_pbr_avg,BL_pbr_avg,SH_pbr_avg,SL_pbr_avg,SMB,HML
0,2023-04-04,0.006634,0.015729,0.010173,0.009385,0.008377,0.004250
1,2023-04-05,-0.002874,0.005084,-0.000961,0.004973,0.002907,-0.008864
2,2023-04-06,-0.009685,-0.008185,-0.008797,-0.006539,-0.006401,-0.011121
3,2023-04-07,-0.000917,0.000808,0.000233,0.002926,0.003213,-0.002551
4,2023-04-10,0.004760,0.004393,-0.006439,-0.003749,-0.014764,-0.002001
...,...,...,...,...,...,...,...
234,2024-03-19,-0.026583,-0.009621,-0.003006,-0.003027,0.012069,-0.023266
235,2024-03-20,0.003264,0.007288,0.003992,0.008088,0.006804,-0.000433
236,2024-03-21,0.019513,0.010174,0.008600,0.007848,0.001604,0.019102
237,2024-03-22,-0.004787,0.003787,0.002175,0.005545,0.008221,-0.007278
238,2024-03-25,-0.008217,0.001042,-0.001873,-0.000865,0.000850,-0.010178

In [431]:
df_merge.loc[0]['SMB']

-0.0013688852169504691

## 배당 성향

In [233]:
# fulldata = pd.merge(manufacture, acc, on='종목명')
# fulldata

         종목코드    종목명          시가총액 기업구분   PBR 1/PBR  sell_rtn
0        5930   삼성전자  3.301290e+14    B  1.27     L       NaN
1        5930   삼성전자  3.301290e+14    B  1.27     L -0.005797
2        5930   삼성전자  3.301290e+14    B  1.27     L  0.007289
3        5930   삼성전자  3.301290e+14    B  1.27     L -0.008683
4        5930   삼성전자  3.301290e+14    B  1.27     L -0.007299
...       ...    ...           ...  ...   ...   ...       ...
156109  30790  비케이탑스  1.920832e+10    S  2.71     L       NaN
156110  30790  비케이탑스  1.920832e+10    S  2.71     L       NaN
156111  30790  비케이탑스  1.920832e+10    S  2.71     L       NaN
156112  30790  비케이탑스  1.920832e+10    S  2.71     L       NaN
156113  30790  비케이탑스  1.920832e+10    S  2.71     L       NaN

[156114 rows x 7 columns]

In [2]:
import pandas as pd
pd.read_csv('csv/리얼 배당성향.csv', encoding='CP949')

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_92796/4083306497.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

            회사명   거래소코드     회계년도   배당성향
0      (주)DB하이텍     990  2022/12  10.12
1      (주)HJ중공업   97230  2022/12   0.00
2      (주)MH에탄올   23150  2022/12  28.62
3    (주)SH에너지화학    2360  2022/12  89.07
4     (주)SIMPAC    9160  2022/12  22.84
..          ...     ...      ...    ...
740    효성중공업(주)  298040  2022/12   0.00
741   효성첨단소재(주)  298050  2022/12  31.53
742    효성티앤씨(주)  298020  2022/12  14.90
743     효성화학(주)  298000  2022/12   0.00
744     흥아해운(주)    3280  2022/12   0.00

[745 rows x 4 columns]

In [240]:
div = pd.read_csv('csv/리얼 배당성향.csv', encoding='CP949')
div['회사명'] = div['회사명'].str.lstrip('(주)')
div['회사명'] = div['회사명'].str.rstrip('(주)')

div.drop(columns=['거래소코드','회계년도'], inplace=True)
div.columns = ['종목명','배당성향']

div

         종목명   배당성향
0      DB하이텍  10.12
1      HJ중공업   0.00
2      MH에탄올  28.62
3    SH에너지화학  89.07
4     SIMPAC  22.84
..       ...    ...
740    효성중공업   0.00
741   효성첨단소재  31.53
742    효성티앤씨  14.90
743     효성화학   0.00
744     흥아해운   0.00

[745 rows x 2 columns]

In [242]:
div = div[(div != 0).all(axis=1)]
div.dropna(inplace=True)
div = div.sort_values(by='배당성향', ascending=False).reset_index(drop=True)

div['배당'] = 0
div

          종목명     배당성향  배당
0      제일연마공업  9915.20   0
1    엘에스에코에너지  2066.34   0
2        케이씨씨   801.24   0
3          효성   624.83   0
4       대성에너지   557.60   0
..        ...      ...  ..
449      대한화섬     2.52   0
450      가온전선     2.21   0
451        전방     1.68   0
452       카카오     1.62   0
453   신화다이나믹스     1.12   0

[454 rows x 3 columns]

In [243]:
div.loc[:135, '배당'] = 'H'
div.loc[300 : 453, '배당'] = 'L'
div

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_75707/2149882975.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'H' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  div.loc[:135, '배당'] = 'H'

          종목명     배당성향 배당
0      제일연마공업  9915.20  H
1    엘에스에코에너지  2066.34  H
2        케이씨씨   801.24  H
3          효성   624.83  H
4       대성에너지   557.60  H
..        ...      ... ..
449      대한화섬     2.52  L
450      가온전선     2.21  L
451        전방     1.68  L
452       카카오     1.62  L
453   신화다이나믹스     1.12  L

[454 rows x 3 columns]

In [244]:
div_data = pd.merge(div, comp, on='종목명')
div_data

       종목명    배당성향 배당    종목코드          시가총액 기업구분
0       효성  624.83  H    4800  1.413870e+12    S
1    대성에너지  557.60  H  117580  2.513500e+11    S
2      지누스  402.19  H   13890  6.615240e+11    S
3      모나미  395.55  H    5360  5.999895e+10    S
4     한국카본  257.22  H   17960  4.857660e+11    S
..     ...     ... ..     ...           ...  ...
317   KG스틸    2.85  L   16380  7.390660e+11    S
318   대한화섬    2.52  L    3830  1.553760e+11    S
319   가온전선    2.21  L     500  1.239990e+11    S
320     전방    1.68  L     950  7.467600e+10    S
321    카카오    1.62  L   35720  2.365130e+13    B

[322 rows x 6 columns]

In [246]:
BH_div = div_data.loc[(div_data['기업구분'] == 'B') & (div_data['배당'] == 'H')]
BL_div = div_data.loc[(div_data['기업구분'] == 'B') & (div_data['배당'] == 'L')]
SH_div = div_data.loc[(div_data['기업구분'] == 'S') & (div_data['배당'] == 'H')]
SL_div = div_data.loc[(div_data['기업구분'] == 'S') & (div_data['배당'] == 'L')]

## 수익률 계산

In [106]:
close = pd.read_csv('csv/월별수익률.csv', encoding='CP949')
# close['month_rtn'] = close['종가(원)'].pct_change()
close

,연월,종목명,종목코드,시장명,종가,최고가(종가),최저가(종가),표준편차,첨도,공왜도,베타,Amihud,Amivest,Zeros,거래량_합계,거래량_일평균,거래대금_합계,거래대금_일평균
0,2022/04,NH올원리츠,400760,KOSPI,5500,5530,5350,0.591666,3.494400,NaN,NaN,0.000563,347873.8094,9.523810,3038507,144691,16503411080,785876718
1,2022/04,코오롱플라스틱,138490,KOSPI,12900,13000,11750,2.654405,-0.622154,NaN,NaN,0.000412,280459.8524,9.523810,9160975,436237,116051251250,5526250060
2,2022/04,한국ANKOR유전,152550,KOSPI,1535,1555,1530,0.359030,-0.874043,NaN,NaN,0.041815,26725.2588,23.809524,339648,16174,522023800,24858276
3,2022/04,쿠쿠홀딩스,192400,KOSPI,18700,19150,17700,1.273356,-0.050315,NaN,NaN,0.001497,42928.3743,14.285714,805035,38335,14796152800,704578705
4,2022/04,LS에코에너지,229640,KOSPI,7990,8250,7920,1.131364,0.197310,NaN,NaN,0.000731,340737.7143,9.523810,3972516,189167,32102812130,1528705340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11023,2023/03,F&F,383220,KOSPI,139500,144000,129900,1.788933,-0.120122,NaN,NaN,0.000094,166251.6549,4.545455,2616569,118935,357938919300,16269950877
11024,2023/03,아세아시멘트,183190,KOSPI,10130,10130,8930,1.750432,2.531098,NaN,NaN,0.001485,139280.5099,9.090909,1598470,72658,14931664980,678712045
11025,2023/03,LS에코에너지,229640,KOSPI,6910,7120,6610,1.204772,2.714643,NaN,NaN,0.001896,130633.0602,9.090909,1309119,59505,9005407680,409336713
11026,2023/03,씨티알모빌리티,308170,KOSPI,16600,16950,14300,3.184463,0.401502,NaN,NaN,0.002123,104142.7224,0.000000,4760898,216404,81443788220,3701990374
11027,2023/03,솔루스첨단소재2우B,33637L,KOSPI,11420,12170,10930,2.000525,5.308317,NaN,NaN,0.033082,8807.3461,9.090909,180729,8215,2129122070,96778276

In [99]:
# company = []
# for i in close.index :
#     company.append(close['회사명'].unique()[i])

# company

IndexError: index 761 is out of bounds for axis 0 with size 761

In [102]:
for i in close.index:
    if len(str(close.loc[i,"종목코드"])) == 3:
        close.loc[i,"종목코드"]='000'+str(close.loc[i,"종목코드"])
    elif len(str(close.loc[i,"종목코드"])) == 4:
        close.loc[i,"종목코드"]='00'+str(close.loc[i,"종목코드"])
    elif len(str(close.loc[i,"종목코드"])) == 5:
        close.loc[i,"종목코드"]='0'+str(close.loc[i,"종목코드"])
    elif len(str(close.loc[i,"종목코드"])) == 2:
        close.loc[i,"종목코드"]='0000'+str(close.loc[i,"종목코드"])

In [123]:
code = close['종목코드'].unique()
code = pd.DataFrame(code)
code.columns = ['종목코드']
code

       종목코드
0    400760
1    138490
2    152550
3    192400
4    229640
..      ...
924  450140
925  45014K
926  45226K
927  451800
928  452260

[929 rows x 1 columns]

In [130]:
company = close[['종목명','종목코드']]
company = company.groupby('종목명')['종목코드'].unique()
company = pd.DataFrame(company)
company

             종목코드
종목명
AJ네트웍스   [095570]
AK홀딩스    [006840]
BGF      [027410]
BGF리테일   [282330]
BNK금융지주  [138930]
...           ...
휴비스      [079980]
휴스틸      [005010]
흥국화재     [000540]
흥국화재우    [000545]
흥아해운     [003280]

[929 rows x 1 columns]

In [117]:
close[close['종목명'] == '흥국화재']

,연월,종목명,종목코드,시장명,종가,최고가(종가),최저가(종가),표준편차,첨도,공왜도,베타,Amihud,Amivest,Zeros,거래량_합계,거래량_일평균,거래대금_합계,거래대금_일평균
854,2022/04,흥국화재,000540,KOSPI,3950,4310,3945,1.808581,4.097944,NaN,NaN,0.002660,203081.0161,9.523810,2675616,127410,11185053095,532621576
1770,2022/05,흥국화재,000540,KOSPI,3855,4050,3525,1.570976,-0.663714,NaN,NaN,0.006898,53555.5979,4.761905,1121686,53414,4217840095,200849528
1936,2022/06,흥국화재,000540,KOSPI,3245,3865,3100,2.671182,3.942324,NaN,NaN,0.008900,53754.9726,0.000000,1095509,54775,3792317065,189615853
3537,2022/07,흥국화재,000540,KOSPI,3315,3365,3140,1.004118,4.913103,NaN,NaN,0.005541,215808.2902,9.523810,2377249,113202,7462424040,355353526
4349,2022/08,흥국화재,000540,KOSPI,3345,3600,3260,1.995974,-0.200717,NaN,NaN,0.013717,28638.0186,9.090909,1146371,52108,3967916040,180359820
4647,2022/09,흥국화재,000540,KOSPI,3090,3490,3090,1.740837,-0.036556,NaN,NaN,0.013532,34851.6707,10.000000,779271,38964,2578368455,128918423
6320,2022/10,흥국화재,000540,KOSPI,2950,3140,2895,1.438966,0.295792,NaN,NaN,0.015535,51054.5065,5.263158,759443,39971,2326461795,122445358
7295,2022/11,흥국화재,000540,KOSPI,3165,3215,2835,1.255551,0.683415,NaN,NaN,0.010505,103416.8792,0.000000,1113435,50611,3300277070,150012594
7450,2022/12,흥국화재,000540,KOSPI,3370,3370,3070,0.965024,1.189426,NaN,NaN,0.005706,825657.4156,0.000000,15972406,760591,59888402133,2851828673
8868,2023/01,흥국화재,000540,KOSPI,3550,3550,3305,1.442344,1.664995,NaN,NaN,0.007362,89962.1909,0.000000,2019903,100995,7159299690,357964985
10085,2023/02,흥국화재,000540,KOSPI,3735,3775,3440,2.146848,5.099572,NaN,NaN,0.007964,68884.8365,5.000000,1800328,90016,6600268565,330013428
10213,2023/03,흥국화재,000540,KOSPI,3180,3870,3150,2.283601,1.094253,NaN,NaN,0.005156,112138.4183,13.636364,1993371,90608,6854371810,311562355

In [448]:
for i in company.index :
    if len(company.loc[i, '종목코드']) == 2 :
        print(i)

In [119]:
c = close['종목명'].unique()
c = pd.DataFrame(c)
c.columns=['종목명']
c

            종목명
0        NH올원리츠
1       코오롱플라스틱
2     한국ANKOR유전
3         쿠쿠홀딩스
4       LS에코에너지
..          ...
924   코오롱모빌리티그룹
925  코오롱모빌리티그룹우
926     한화갤러리아우
927        한화리츠
928      한화갤러리아

[929 rows x 1 columns]

In [124]:
code['종목명'] = c['종목명']

In [125]:
code

       종목코드         종목명
0    400760      NH올원리츠
1    138490     코오롱플라스틱
2    152550   한국ANKOR유전
3    192400       쿠쿠홀딩스
4    229640     LS에코에너지
..      ...         ...
924  450140   코오롱모빌리티그룹
925  45014K  코오롱모빌리티그룹우
926  45226K     한화갤러리아우
927  451800        한화리츠
928  452260      한화갤러리아

[929 rows x 2 columns]

In [126]:
import FinanceDataReader as fdr

fdr.DataReader('058820', '2011-01-01', '2021-12-31')

            Open  High   Low  Close   Volume    Change
Date
2011-01-03  1426  1440  1392   1394   439492 -0.023125
2011-01-04  1417  1417  1325   1329   671688 -0.046628
2011-01-05  1333  1351  1260   1321   470690 -0.006020
2011-01-06  1287  1333  1276   1333   422197  0.009084
2011-01-07  1300  1363  1287   1319   167534 -0.010503
...          ...   ...   ...    ...      ...       ...
2021-12-24  3760  3780  3710   3720   322797 -0.009321
2021-12-27  3720  3975  3720   3910  3047519  0.051075
2021-12-28  3895  3935  3835   3890  1171808 -0.005115
2021-12-29  3890  3990  3820   3830  1079522 -0.015424
2021-12-30  3845  3850  3790   3835   469510  0.001305

[2711 rows x 6 columns]

In [127]:
code.loc[1, '종목코드']

'138490'

In [389]:
sell = []
for i in code.index :
    df = fdr.DataReader(str(code.loc[i, '종목코드']), '2023-04-01', '2024-03-25')
    sell.append(df)

In [390]:
sell

[            Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  3495  3515  3460   3515   85518  0.008608
 2023-04-04  3525  3555  3505   3555   83509  0.011380
 2023-04-05  3555  3560  3445   3490  228903 -0.018284
 2023-04-06  3490  3490  3390   3430  227726 -0.017192
 2023-04-07  3430  3430  3370   3375  193698 -0.016035
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  3560  3560  3460   3535   52441 -0.004225
 2024-03-20  3540  3560  3525   3545   17406  0.002829
 2024-03-21  3550  3595  3540   3595   24570  0.014104
 2024-03-22  3600  3615  3575   3615   43847  0.005563
 2024-03-25  3620  3630  3610   3630   33818  0.004149

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  10460  10700  10370  10410   350732  0.001925
 2023-04-04  10410  11200  10320  10570  1059115  0.015370
 2023-04-05  10560  10560  10350  10490   235904 -0.007569
 2023-04-06  10440  10440  10080  10150   360958 -0.032412
 2023-04-07  10150  10330  10090  10260   202429  0.010837
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19   7400   7590   7350   7500   128207  0.009421
 2024-03-20   7560   7560   7450   7500    65156  0.000000
 2024-03-21   7570   7680   7460   7550   143483  0.006667
 2024-03-22   7580   7580   7500   7520    41287 -0.003974
 2024-03-25   7480   7570   7450   7490    42639 -0.003989

 [240 rows x 6 columns],
             Open  High  Low  Close     Volume    Change
 Date
 2023-04-03   168   221  157    221   66116751  0.300000
 2023-04-04   255   287  243    287   54757115  0.298643
 2023-04-05   310   373  310    373  153406540  0.299652
 2023-04-06   412   484  373    484  103750259  0.297587
 2023-04-07   577   629  531    629   71978478  0.299587
 ...          ...   ...  ...    ...        ...       ...
 2024-03-19   361   364  352    356    1210914  0.000000
 2024-03-20   357   358  351    351     974466 -0.014045
 2024-03-21   352   355  351    351     742664  0.000000
 2024-03-22   353   354  349    349     878201 -0.005698
 2024-03-25   351   360  348    350    1202084  0.002865

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  15670  15680  15430  15580   19135 -0.004473
 2023-04-04  15700  16020  15510  15960   26395  0.024390
 2023-04-05  15890  16100  15590  15610   48741 -0.021930
 2023-04-06  15610  15610  15370  15370   23128 -0.015375
 2023-04-07  15370  15400  15180  15270   24500 -0.006506
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  18360  18500  18050  18380   48403  0.004921
 2024-03-20  18640  19000  18550  18920  126613  0.029380
 2024-03-21  18930  18970  18270  18580   59783 -0.017970
 2024-03-22  18570  18610  18200  18560   37794 -0.001076
 2024-03-25  18560  18560  18000  18260   42587 -0.016164

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03   6900   7000   6850   6940   83369  0.004342
 2023-04-04   7000   7150   6940   7100  222728  0.023055
 2023-04-05   7050   7070   6970   6990   80874 -0.015493
 2023-04-06   6980   6990   6880   6990   44541  0.000000
 2023-04-07   6990   7010   6880   6960   63047 -0.004292
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  19120  19360  18600  18800  236881 -0.012086
 2024-03-20  18800  19100  18570  18750  219691 -0.002660
 2024-03-21  18850  18890  18350  18350  230421 -0.021333
 2024-03-22  18320  18430  17980  18160  253652 -0.010354
 2024-03-25  18200  18430  17980  18050  192339 -0.006057

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  22100  22800  22050  22550   488853  0.008949
 2023-04-04  22850  24200  22850  23200  1202351  0.028825
 2023-04-05  23700  24500  23650  24200  1051928  0.043103
 2023-04-06  24500  24850  23550  23700   653577 -0.020661
 2023-04-07  24000  24150  23400  23500   386857 -0.008439
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  27150  27300  26400  26450   432366 -0.022181
 2024-03-20  26550  26600  25600  25850   640093 -0.022684
 2024-03-21  25900  26050  25100  25350   763868 -0.019342
 2024-03-22  25500  25850  25400  25750   311175  0.015779
 2024-03-25  25750  25800  25300  25350   187573 -0.015534

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  20800  20800  20050  20150    46285 -0.026570
 2023-04-04  20250  20400  19680  19890    54507 -0.012903
 2023-04-05  20250  20550  19770  20350    64325  0.023127
 2023-04-06  20300  20300  19720  20000    52589 -0.017199
 2023-04-07  20100  20600  20050  20500    45188  0.025000
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  41500  41550  39100  39700   320786 -0.050239
 2024-03-20  40500  40700  38550  39750   238333  0.001259
 2024-03-21  41100  44500  41100  44100  1188616  0.109434
 2024-03-22  43950  44250  41550  41650   326996 -0.055556
 2024-03-25  42100  43600  40400  40750   363656 -0.021609

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  132000  132000  123400  124200   56409 -0.045350
 2023-04-04  125300  125300  121900  123100   31630 -0.008857
 2023-04-05  123100  124000  119800  120300   31484 -0.022746
 2023-04-06  120300  120300  116100  116300   36377 -0.033250
 2023-04-07  116500  117400  114900  115400   30085 -0.007739
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19   62400   62700   60800   61600    9496 -0.019108
 2024-03-20   61200   62600   61200   61500    6327 -0.001623
 2024-03-21   61200   62800   61200   61700    9394  0.003252
 2024-03-22   61700   62800   61000   62500    5670  0.012966
 2024-03-25   62600   62900   61400   61700    8320 -0.012800

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  432000  435000  424500  426500   24501 -0.012731
 2023-04-04  428000  429000  416000  419000   26527 -0.017585
 2023-04-05  420000  421500  414000  419500   18585  0.001193
 2023-04-06  419500  419500  411000  411500   25897 -0.019070
 2023-04-07  414000  416500  410000  412000   18626  0.001215
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  340500  340500  335000  338000    9191 -0.007342
 2024-03-20  339500  339500  331500  334000   12954 -0.011834
 2024-03-21  334500  339500  334500  339000   13795  0.014970
 2024-03-22  339000  339000  334500  335000   12969 -0.011799
 2024-03-25  334000  335000  323500  325000   46108 -0.029851

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  63300  64000  61900  62100  104196 -0.018957
 2023-04-04  62200  64200  61400  63800  131232  0.027375
 2023-04-05  63700  65000  62900  63700  119627 -0.001567
 2023-04-06  63800  65200  62800  62900  120603 -0.012559
 2023-04-07  62900  63800  62300  62600   81564 -0.004769
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  93900  94700  92700  93400   81729 -0.010593
 2024-03-20  94300  94800  92300  93400   83986  0.000000
 2024-03-21  94200  96400  94100  96000  147529  0.027837
 2024-03-22  95400  95800  94500  94600   71040 -0.014583
 2024-03-25  95300  96300  94600  95700  109431  0.011628

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  23700  24100  23150  23700   627421  0.000000
 2023-04-04  23750  24100  23350  23350   561066 -0.014768
 2023-04-05  23150  23850  23050  23450   395938  0.004283
 2023-04-06  23200  23200  22600  22850   386636 -0.025586
 2023-04-07  23200  24700  23200  24450  1198659  0.070022
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  22850  22850  22500  22800   276316 -0.004367
 2024-03-20  22800  23850  22750  23700   888477  0.039474
 2024-03-21  24250  24600  23900  24250  1160766  0.023207
 2024-03-22  24450  24500  23800  24300   666205  0.002062
 2024-03-25  24250  24350  23750  23800   394673 -0.020576

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  588000  590000  577000  586000  330892  0.003425
 2023-04-04  586000  598000  572000  575000  444861 -0.018771
 2023-04-05  575000  589000  574000  588000  235578  0.022609
 2023-04-06  587000  590000  578000  580000  278416 -0.013605
 2023-04-07  581000  590000  579000  580000  366225  0.000000
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  412000  412000  402000  403000  118968 -0.011043
 2024-03-20  405000  410000  404000  407500  114805  0.011166
 2024-03-21  409500  414000  409000  413500  154423  0.014724
 2024-03-22  410500  415500  409000  413500  136480  0.000000
 2024-03-25  416500  417000  412000  414500  162037  0.002418

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  138600  142000  138500  140600  108841  0.007885
 2023-04-04  143600  144400  138600  143400  146566  0.019915
 2023-04-05  144200  144500  139700  140400  116930 -0.020921
 2023-04-06  140400  140400  135700  136600  141618 -0.027066
 2023-04-07  136900  138200  135000  137100   94393  0.003660
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19   68000   68900   67500   68000  104010 -0.005848
 2024-03-20   68600   68600   67200   67900  122988 -0.001471
 2024-03-21   68400   68800   67500   68200  165293  0.004418
 2024-03-22   67600   71400   67600   71200  171888  0.043988
 2024-03-25   71000   71000   69400   69500   58391 -0.023876

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  8530  8570  8510   8530   84550  0.000000
 2023-04-04  8530  8550  8500   8540  112148  0.001172
 2023-04-05  8550  8550  8500   8500  121191 -0.004684
 2023-04-06  8510  8520  8480   8500  160722  0.000000
 2023-04-07  8510  8510  8440   8460  135930 -0.004706
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  6990  7000  6940   6980   41493 -0.001431
 2024-03-20  6980  7000  6950   7000   43203  0.002865
 2024-03-21  6970  7020  6970   7000   59823  0.000000
 2024-03-22  7020  7020  6980   7010   91070  0.001429
 2024-03-25  7020  7030  6980   7010   45290  0.000000

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  3795  3840  3695   3720   33095 -0.005348
 2023-04-04  3760  3770  3700   3720   42303  0.000000
 2023-04-05  3740  3755  3690   3720   41122  0.000000
 2023-04-06  3720  3740  3680   3740   17514  0.005376
 2023-04-07  3745  3750  3675   3685   35008 -0.014706
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  3960  4000  3905   3985   22579  0.007585
 2024-03-20  4000  4045  3960   4045   33487  0.015056
 2024-03-21  4075  4075  4020   4060   36002  0.003708
 2024-03-22  4060  4160  4045   4155   78887  0.023399
 2024-03-25  4155  4160  4135   4155   21657  0.000000

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  11360  11460  11000  11000   94398 -0.029982
 2023-04-04  11000  11750  10940  11650  194105  0.059091
 2023-04-05  11740  12900  11590  11720  733001  0.006009
 2023-04-06  11830  12050  11350  11420  153414 -0.025597
 2023-04-07  11610  12150  11460  11950  179783  0.046410
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19   8680   8830   8510   8700   36414 -0.002294
 2024-03-20   8690   9160   8590   9000  120764  0.034483
 2024-03-21   9060   9070   8770   8890   50753 -0.012222
 2024-03-22   8870   8950   8820   8880   50755 -0.001125
 2024-03-25   8880   9060   8850   8890   63901  0.001126

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  32600  33300  32500  32950  153082  0.018547
 2023-04-04  33000  33350  32700  33050  176939  0.003035
 2023-04-05  33400  33400  32900  32900   99315 -0.004539
 2023-04-06  33000  33250  32200  32300  227587 -0.018237
 2023-04-07  32450  32950  32100  32850  111348  0.017028
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  34650  36200  34650  35750  188494  0.021429
 2024-03-20  36200  36400  35300  35650   95677 -0.002797
 2024-03-21  36100  36650  35900  36400  115646  0.021038
 2024-03-22  36200  36950  36100  36750  107959  0.009615
 2024-03-25  36750  36750  35950  36050   97039 -0.019048

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  4085  4130  4030   4120   59587  0.008568
 2023-04-04  4120  4230  4120   4220  138596  0.024272
 2023-04-05  4225  4225  4120   4200   67699 -0.004739
 2023-04-06  4155  4265  4090   4180   79845 -0.004762
 2023-04-07  4180  4245  4110   4135   62630 -0.010766
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  4220  4220  4095   4115   94687 -0.027187
 2024-03-20  4080  4150  4080   4115   43826  0.000000
 2024-03-21  4220  4225  4130   4220   32692  0.025516
 2024-03-22  4205  4280  4175   4215   34126 -0.001185
 2024-03-25  4215  4245  4145   4195   34632 -0.004745

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  12720  12950  12220  12280   287092 -0.035350
 2023-04-04  12360  13740  12360  13340  2086736  0.086319
 2023-04-05  13300  13720  13170  13510   760919  0.012744
 2023-04-06  13510  15200  13510  14560  4172651  0.077720
 2023-04-07  14620  14770  14110  14690   847144  0.008929
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  13830  13900  13390  13510    91529 -0.019594
 2024-03-20  13510  13720  13150  13170   100869 -0.025167
 2024-03-21  13300  13400  12930  13000   128616 -0.012908
 2024-03-22  13010  13440  13010  13330   145524  0.025385
 2024-03-25  13330  13680  13060  13630   141717  0.022506

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  16890  17230  16780  17040  167750  0.026506
 2023-04-04  16920  17120  16620  16830   97559 -0.012324
 2023-04-05  16830  17120  16750  16960   71957  0.007724
 2023-04-06  16960  16960  16380  16750   60880 -0.012382
 2023-04-07  16750  17000  16540  16640   47176 -0.006567
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19   9850   9950   9700   9800   12818  0.000000
 2024-03-20   9840   9840   9620   9820   10468  0.002041
 2024-03-21   9820   9900   9790   9850   20062  0.003055
 2024-03-22   9850   9900   9760   9900    7075  0.005076
 2024-03-25   9950  10030   9840   9920    9425  0.002020

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  53500  53700  51900  52900  174354 -0.001887
 2023-04-04  54100  54600  52800  52900  260202  0.000000
 2023-04-05  52600  53100  51700  52100  175291 -0.015123
 2023-04-06  51800  53400  50900  51100  224038 -0.019194
 2023-04-07  51900  52100  51100  51400  124203  0.005871
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  22850  22850  22600  22750   21840 -0.004376
 2024-03-20  22650  22750  22350  22550   39563 -0.008791
 2024-03-21  22600  22850  22500  22700   37131  0.006652
 2024-03-22  22550  22800  22350  22700   24810  0.000000
 2024-03-25  22650  22700  22250  22450   37497 -0.011013

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  3805  3835  3805   3825   12724  0.001309
 2023-04-04  3850  3850  3755   3795   46584 -0.007843
 2023-04-05  3795  3810  3770   3795   21974  0.000000
 2023-04-06  3790  3805  3780   3800    4395  0.001318
 2023-04-07  3800  3815  3760   3800    8982  0.000000
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  3865  3865  3840   3850   37571  0.000000
 2024-03-20  3875  3875  3840   3850   27641  0.000000
 2024-03-21  3855  3890  3850   3865   55235  0.003896
 2024-03-22  3865  3915  3860   3910   41421  0.011643
 2024-03-25  3910  3930  3875   3910   45616  0.000000

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  3510  3534  3475   3515   29166 -0.001420
 2023-04-04  3564  3564  3505   3520   19774  0.001422
 2023-04-05  3524  3534  3500   3505   60397 -0.004261
 2023-04-06  3504  3514  3490   3500   20607 -0.001427
 2023-04-07  3519  3524  3470   3480   18065 -0.005714
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  3205  3220  3185   3220   50187  0.004680
 2024-03-20  3215  3245  3210   3235   28796  0.004658
 2024-03-21  3255  3260  3230   3240   65247  0.001546
 2024-03-22  3240  3300  3235   3300   90015  0.018519
 2024-03-25  3280  3340  3265   3335   54305  0.010606

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  3530  3560  3505   3525  100836 -0.004237
 2023-04-04  3580  3620  3515   3530   79549  0.001418
 2023-04-05  3530  3530  3460   3485  250121 -0.012748
 2023-04-06  3480  3485  3410   3425   96268 -0.017217
 2023-04-07  3450  3450  3385   3390   82771 -0.010219
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  3510  3535  3485   3535   49995  0.005690
 2024-03-20  3525  3565  3495   3555   78965  0.005658
 2024-03-21  3585  3585  3550   3560   74248  0.001406
 2024-03-22  3560  3600  3550   3600  110307  0.011236
 2024-03-25  3620  3645  3575   3645  140364  0.012500

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  12980  13170  12670  13010   47482  0.017997
 2023-04-04  12950  13670  12800  13150  191590  0.010761
 2023-04-05  13090  13260  12910  12950   28446 -0.015209
 2023-04-06  12970  13200  12780  12890   34249 -0.004633
 2023-04-07  12910  12910  12700  12700   33876 -0.014740
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  13560  13790  13410  13650   25907  0.007380
 2024-03-20  13650  13840  13550  13800  833821  0.010989
 2024-03-21  13850  13900  13310  13420   79711 -0.027536
 2024-03-22  13380  13380  13000  13030   41043 -0.029061
 2024-03-25  13030  13130  12700  13050   39842  0.001535

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  1544  1554  1533   1540  107570  0.009174
 2023-04-04  1525  1568  1525   1564  124414  0.015584
 2023-04-05  1551  1583  1551   1560  119030 -0.002558
 2023-04-06  1550  1553  1525   1525  118239 -0.022436
 2023-04-07  1525  1532  1514   1524   86087 -0.000656
 ...          ...   ...   ...    ...     ...       ...
 2024-03-19  2015  2030  1988   2000  563261 -0.014778
 2024-03-20  2000  2015  1983   2005  443006  0.002500
 2024-03-21  2005  2025  1999   2015  328473  0.004988
 2024-03-22  2000  2025  1992   2000  394743 -0.007444
 2024-03-25  2000  2060  1999   2055  710293  0.027500

 [240 rows x 6 columns],
             Open  High  Low  Close  Volume    Change
 Date
 2023-04-03   947   955  930    948  423048  0.001056
 2023-04-04   968   968  931    951  282442  0.003165
 2023-04-05   948   953  937    949  118462 -0.002103
 2023-04-06   945   945  918    924  176711 -0.026344
 2023-04-07   925   937  920    933   84027  0.009740
 ...          ...   ...  ...    ...     ...       ...
 2024-03-19   914   915  896    915  123001  0.000000
 2024-03-20   908   915  890    899  181859 -0.017486
 2024-03-21   899   906  895    900  150086  0.001112
 2024-03-22   903   908  895    906  108149  0.006667
 2024-03-25   910   917  901    909  266970  0.003311

 [240 rows x 6 columns],
             Open  High   Low  Close  Volume    Change
 Date
 2023-04-03  4130  4145  4085   4090   12549 -0.009685
 2023-04-04  4095  4135  4085   4100   19613  0.002445
 2023-04-05  4120  4120  4070   4075   56435 -0.006098
 2023-04-06  4085  4100  4035   4065   59344 -0.002454
 2023-04-07  4140  4140  4020   4030   41022 -0.008610
 ...          ...   ...   ...    ...     ...       ...

In [391]:
for i in code.index :
    sell[i]['종목코드'] = code.loc[i, '종목코드']
    sell[i]['종목명'] = code.loc[i, '종목명']

In [393]:
code_data = pd.concat(sell)
# a = code_data.loc['2023-02-24' : ]
# a[a['종목명'] == '한화솔루션']

In [394]:
code_data['sell_rtn'] = code_data.groupby(['종목코드']).Close.pct_change()
# df = code_data.groupby(['종목코드'])
# code_data['sell_rtn'] = code_data.groupby(['종목코드']).np.log(code_data.Low) - np.log(code_data.Low.shift(1))
# code_data['sell_rtn'] = df.np.log(df.Low) - np.log(df.Low.shift(1))
code_data

,Open,High,Low,Close,Volume,Change,종목코드,종목명,sell_rtn
Date,,,,,,,,,
2023-04-03,3495,3515,3460,3515,85518,0.008608,400760,NH올원리츠,NaN
2023-04-04,3525,3555,3505,3555,83509,0.011380,400760,NH올원리츠,0.011380
2023-04-05,3555,3560,3445,3490,228903,-0.018284,400760,NH올원리츠,-0.018284
2023-04-06,3490,3490,3390,3430,227726,-0.017192,400760,NH올원리츠,-0.017192
2023-04-07,3430,3430,3370,3375,193698,-0.016035,400760,NH올원리츠,-0.016035
...,...,...,...,...,...,...,...,...,...
2024-03-19,1465,1529,1440,1482,5463523,0.017159,452260,한화갤러리아,0.017159
2024-03-20,1482,1549,1478,1507,4370477,0.016869,452260,한화갤러리아,0.016869
2024-03-21,1519,1535,1493,1493,2142983,-0.009290,452260,한화갤러리아,-0.009290
2024-03-22,1500,1514,1486,1486,1180297,-0.004689,452260,한화갤러리아,-0.004689
2024-03-25,1487,1522,1473,1505,2302019,0.012786,452260,한화갤러리아,0.012786

In [395]:
code_data.iloc[280:300, :]

,Open,High,Low,Close,Volume,Change,종목코드,종목명,sell_rtn
Date,,,,,,,,,
2023-06-01,9900,9980,9860,9890,73878,-0.001010,138490,코오롱플라스틱,-0.001010
2023-06-02,9910,9960,9870,9940,81484,0.005056,138490,코오롱플라스틱,0.005056
2023-06-05,10000,10130,9990,10030,116246,0.009054,138490,코오롱플라스틱,0.009054
2023-06-07,10060,10090,9950,9980,124751,-0.004985,138490,코오롱플라스틱,-0.004985
2023-06-08,9950,10070,9900,10060,106741,0.008016,138490,코오롱플라스틱,0.008016
2023-06-09,10100,10110,10020,10060,72631,0.000000,138490,코오롱플라스틱,0.000000
2023-06-12,10050,10090,9930,9980,107880,-0.007952,138490,코오롱플라스틱,-0.007952
2023-06-13,9980,10030,9940,9940,105258,-0.004008,138490,코오롱플라스틱,-0.004008
2023-06-14,9960,9990,9800,9840,148011,-0.010060,138490,코오롱플라스틱,-0.010060
2023-06-15,9880,9920,9500,9570,201581,-0.027439,138490,코오롱플라스틱,-0.027439
2023-06-16,9530,9640,9530,9580,95709,0.001045,138490,코오롱플라스틱,0.001045
2023-06-19,9520,9590,9430,9480,120521,-0.010438,138490,코오롱플라스틱,-0.010438
2023-06-20,9480,9720,9430,9630,99476,0.015823,138490,코오롱플라스틱,0.015823
2023-06-21,9670,9750,9540,9550,90408,-0.008307,138490,코오롱플라스틱,-0.008307
2023-06-22,9540,10040,9500,9890,293101,0.035602,138490,코오롱플라스틱,0.035602
2023-06-23,9980,9980,9660,9660,107456,-0.023256,138490,코오롱플라스틱,-0.023256
2023-06-26,9640,9730,9500,9610,67807,-0.005176,138490,코오롱플라스틱,-0.005176
2023-06-27,9560,9680,9510,9680,73406,0.007284,138490,코오롱플라스틱,0.007284
2023-06-28,9720,9780,9670,9690,61737,0.001033,138490,코오롱플라스틱,0.001033
2023-06-29,9740,9740,9440,9490,86339,-0.020640,138490,코오롱플라스틱,-0.020640

In [396]:
code_data

,Open,High,Low,Close,Volume,Change,종목코드,종목명,sell_rtn
Date,,,,,,,,,
2023-04-03,3495,3515,3460,3515,85518,0.008608,400760,NH올원리츠,NaN
2023-04-04,3525,3555,3505,3555,83509,0.011380,400760,NH올원리츠,0.011380
2023-04-05,3555,3560,3445,3490,228903,-0.018284,400760,NH올원리츠,-0.018284
2023-04-06,3490,3490,3390,3430,227726,-0.017192,400760,NH올원리츠,-0.017192
2023-04-07,3430,3430,3370,3375,193698,-0.016035,400760,NH올원리츠,-0.016035
...,...,...,...,...,...,...,...,...,...
2024-03-19,1465,1529,1440,1482,5463523,0.017159,452260,한화갤러리아,0.017159
2024-03-20,1482,1549,1478,1507,4370477,0.016869,452260,한화갤러리아,0.016869
2024-03-21,1519,1535,1493,1493,2142983,-0.009290,452260,한화갤러리아,-0.009290
2024-03-22,1500,1514,1486,1486,1180297,-0.004689,452260,한화갤러리아,-0.004689
2024-03-25,1487,1522,1473,1505,2302019,0.012786,452260,한화갤러리아,0.012786

In [397]:
acc = code_data.drop(columns=['Open','High','Low','Volume','Change','종목코드'])
acc['Date'] = acc.index
# acc.dropna(axis=True, inplace=True)
acc

            Close     종목명  sell_rtn       Date
Date
2023-04-03   3515  NH올원리츠       NaN 2023-04-03
2023-04-04   3555  NH올원리츠  0.011380 2023-04-04
2023-04-05   3490  NH올원리츠 -0.018284 2023-04-05
2023-04-06   3430  NH올원리츠 -0.017192 2023-04-06
2023-04-07   3375  NH올원리츠 -0.016035 2023-04-07
...           ...     ...       ...        ...
2024-03-19   1482  한화갤러리아  0.017159 2024-03-19
2024-03-20   1507  한화갤러리아  0.016869 2024-03-20
2024-03-21   1493  한화갤러리아 -0.009290 2024-03-21
2024-03-22   1486  한화갤러리아 -0.004689 2024-03-22
2024-03-25   1505  한화갤러리아  0.012786 2024-03-25

[222960 rows x 4 columns]

In [363]:
# code_data.drop(columns=['Open','High','Low','Volume','Change','종목코드'])

            Close     종목명
Date
2022-04-01   5360  NH올원리츠
2022-04-04   5370  NH올원리츠
2022-04-05   5350  NH올원리츠
2022-04-06   5350  NH올원리츠
2022-04-07   5370  NH올원리츠
...           ...     ...
2023-05-24   1653  한화갤러리아
2023-05-25   1641  한화갤러리아
2023-05-26   1630  한화갤러리아
2023-05-30   1637  한화갤러리아
2023-05-31   1653  한화갤러리아

[266618 rows x 2 columns]

In [398]:
acc[acc['sell_rtn'] == np.inf]

Empty DataFrame
Columns: [Close, 종목명, sell_rtn, Date]
Index: []