In [2]:
import pandas as pd

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_84128/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [43]:
manufacture = pd.read_csv('csv/manufacture.csv')
manufacture.drop(columns='Unnamed: 0', inplace=True)
manufacture

       종목코드       종목명          시가총액 기업구분    PBR 1/PBR
0      5930      삼성전자  3.301290e+14    B   1.27     L
1    207940  삼성바이오로직스  5.843390e+13    B  11.01     L
2      6400     삼성SDI  4.063980e+13    B   2.69     L
3       270        기아  2.403800e+13    B   0.68     H
4     35720       카카오  2.365130e+13    B   2.31     L
..      ...       ...           ...  ...    ...   ...
538    1210      금호전기  2.534986e+10    S   0.60     H
539   25620   제이준코스메틱  2.321030e+10    S   0.38     H
540   71950       코아스  2.256226e+10    S   1.20     L
541    8500      일정실업  1.968000e+10    S   1.04     L
542   30790     비케이탑스  1.920832e+10    S   2.71     L

[543 rows x 6 columns]

In [45]:
for i in manufacture.index:
    if len(str(manufacture.loc[i,"종목코드"])) == 3:
        manufacture.loc[i,"종목코드"]='000'+str(manufacture.loc[i,"종목코드"])
    elif len(str(manufacture.loc[i,"종목코드"])) == 4:
        manufacture.loc[i,"종목코드"]='00'+str(manufacture.loc[i,"종목코드"])
    elif len(str(manufacture.loc[i,"종목코드"])) == 5:
        manufacture.loc[i,"종목코드"]='0'+str(manufacture.loc[i,"종목코드"])
    elif len(str(manufacture.loc[i,"종목코드"])) == 2:
        manufacture.loc[i,"종목코드"]='0000'+str(manufacture.loc[i,"종목코드"])

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_84128/654224630.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '005930' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  manufacture.loc[i,"종목코드"]='00'+str(manufacture.loc[i,"종목코드"])

In [46]:
code = manufacture['종목코드'].unique()
code = pd.DataFrame(code)
code.columns = ['종목코드']

code

       종목코드
0    005930
1    207940
2    006400
3    000270
4    035720
..      ...
538  001210
539  025620
540  071950
541  008500
542  030790

[543 rows x 1 columns]

In [47]:
company = manufacture[['종목명','종목코드']]
company = company.groupby('종목명')['종목코드'].unique()
company = pd.DataFrame(company)

company

            종목코드
종목명
AJ네트웍스  [095570]
CS홀딩스   [000590]
DB하이텍   [000990]
HD현대    [267250]
HJ중공업   [097230]
...          ...
후성      [093370]
휠라홀딩스   [081660]
휴비스     [079980]
휴스틸     [005010]
흥아해운    [003280]

[543 rows x 1 columns]

In [48]:
name = manufacture['종목명'].unique()
name = pd.DataFrame(name)
name.columns=['종목명']
name

          종목명
0        삼성전자
1    삼성바이오로직스
2       삼성SDI
3          기아
4         카카오
..        ...
538      금호전기
539   제이준코스메틱
540       코아스
541      일정실업
542     비케이탑스

[543 rows x 1 columns]

In [49]:
code['종목명'] = name['종목명']
code

       종목코드       종목명
0    005930      삼성전자
1    207940  삼성바이오로직스
2    006400     삼성SDI
3    000270        기아
4    035720       카카오
..      ...       ...
538  001210      금호전기
539  025620   제이준코스메틱
540  071950       코아스
541  008500      일정실업
542  030790     비케이탑스

[543 rows x 2 columns]

In [50]:
import FinanceDataReader as fdr

sell = []
for i in code.index :
    df = fdr.DataReader(str(code.loc[i, '종목코드']), '2023-04-01', '2024-03-25')
    sell.append(df)

sell

[             Open   High    Low  Close    Volume    Change
 Date
 2023-04-03  64000  64000  63000  63100  11973133 -0.014062
 2023-04-04  63400  63800  62800  63600  11120514  0.007924
 2023-04-05  63700  64000  63400  63900   9176149  0.004717
 2023-04-06  63500  63600  62300  62300  14992747 -0.025039
 2023-04-07  63800  65200  63800  65000  27476120  0.043339
 ...           ...    ...    ...    ...       ...       ...
 2024-03-19  72300  73000  71700  72800  15376066  0.000000
 2024-03-20  73700  77200  73400  76900  50106297  0.056319
 2024-03-21  79200  79300  77700  79300  44569799  0.031209
 2024-03-22  79600  79900  77800  78900  26724761 -0.005044
 2024-03-25  79600  79800  77800  78200  18703996 -0.008872

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  789000  793000  777000  778000   59605 -0.012690
 2023-04-04  780000  788000  777000  788000   44466  0.012853
 2023-04-05  788000  795000  781000  788000   38411  0.000000
 2023-04-06  790000  824000  790000  805000  169315  0.021574
 2023-04-07  804000  805000  792000  796000   61342 -0.011180
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  860000  861000  845000  848000   58733 -0.012806
 2024-03-20  854000  865000  846000  850000   67582  0.002358
 2024-03-21  853000  858000  830000  857000   76873  0.008235
 2024-03-22  851000  856000  840000  840000   52133 -0.019837
 2024-03-25  847000  852000  835000  840000   47393  0.000000

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  750000  750000  730000  745000  222650  0.013605
 2023-04-04  740000  750000  724000  726000  208636 -0.025503
 2023-04-05  730000  787000  727000  778000  470031  0.071625
 2023-04-06  764000  766000  741000  745000  402833 -0.042416
 2023-04-07  742000  747000  731000  738000  259085 -0.009396
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  451500  454500  438500  451000  655915  0.015766
 2024-03-20  450500  471500  445500  453000  910857  0.004435
 2024-03-21  456000  465000  454000  455500  537490  0.005519
 2024-03-22  454500  475000  453500  472500  779394  0.037322
 2024-03-25  478000  494500  475000  486000  840495  0.028571

 [240 rows x 6 columns],
               Open    High     Low   Close   Volume    Change
 Date
 2023-04-03   81500   81600   80400   81200   807758  0.002469
 2023-04-04   80600   81700   79700   80100  1009704 -0.013547
 2023-04-05   80200   81800   80100   81300  1013013  0.014981
 2023-04-06   82000   83000   81000   81000  1364098 -0.003690
 2023-04-07   80600   81500   80000   80100  1128013 -0.011111
 ...            ...     ...     ...     ...      ...       ...
 2024-03-19  123200  123600  118200  118900  3390443 -0.071094
 2024-03-20  119500  120300  115100  115700  2379123 -0.026913
 2024-03-21  117300  118000  115500  115700  2960845  0.000000
 2024-03-22  116200  116800  112100  112900  2811721 -0.024201
 2024-03-25  113100  113500  111000  111500  1550861 -0.012400

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  61400  61600  59900  60200  1683150 -0.014730
 2023-04-04  60200  60800  59800  60700  1380518  0.008306
 2023-04-05  60500  61200  60200  60500  1227329 -0.003295
 2023-04-06  60100  60100  58500  58600  2659408 -0.031405
 2023-04-07  58600  59200  58100  58600  1650319  0.000000
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  52700  52800  51700  52000  1116159 -0.018868
 2024-03-20  52400  53200  52300  52900   869967  0.017308
 2024-03-21  53900  54200  52800  53600  1359646  0.013233
 2024-03-22  53600  54300  53300  53600   881388  0.000000
 2024-03-25  53400  54500  53100  53800   717693  0.003731

 [240 rows x 6 columns],
               Open    High     Low   Close   Volume    Change
 Date
 2023-04-03  151400  154300  149700  150000   675050  0.001335
 2023-04-04  150000  159100  149400  159000  1013981  0.060000
 2023-04-05  159300  163000  157500  158600   713779 -0.002516
 2023-04-06  160900  163000  159200  159500   727285  0.005675
 2023-04-07  160400  161000  158100  159500   364832  0.000000
 ...            ...     ...     ...     ...      ...       ...
 2024-03-19  181000  184800  180500  184400   614411  0.010411
 2024-03-20  185300  185500  183000  183100   374043 -0.007050
 2024-03-21  185000  185800  183200  185800   595624  0.014746
 2024-03-22  185600  188900  185500  188200   571289  0.012917
 2024-03-25  190200  192400  188900  188900   646054  0.003719

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  108200  109100  108100  108200  175895  0.000000
 2023-04-04  108800  109400  107700  108400  203558  0.001848
 2023-04-05  108700  109600  108400  109200  147336  0.007380
 2023-04-06  109200  109200  107100  107100  245745 -0.019231
 2023-04-07  107300  107900  106600  106900  193663 -0.001867
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  152200  152800  149800  150000  458423 -0.014455
 2024-03-20  151600  156300  151600  156200  652765  0.041333
 2024-03-21  159300  165000  158100  165000  694595  0.056338
 2024-03-22  163700  166400  159500  160000  578344 -0.030303
 2024-03-25  159700  159800  157700  158500  412842 -0.009375

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  216500  217000  213000  214000  183488 -0.009259
 2023-04-04  215500  217000  214000  215000  146996  0.004673
 2023-04-05  215500  218500  215000  218000  132562  0.013953
 2023-04-06  218000  219500  215500  216000  176930 -0.009174
 2023-04-07  215500  215500  213000  213500  168018 -0.011574
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  265000  265500  253500  253500  392572 -0.054104
 2024-03-20  257500  259000  249000  253000  376506 -0.001972
 2024-03-21  257000  267000  256500  266000  321963  0.051383
 2024-03-22  264500  267000  260000  262000  300132 -0.015038
 2024-03-25  259500  264000  257000  258000  183402 -0.015267

 [240 rows x 6 columns],
               Open    High     Low   Close   Volume    Change
 Date
 2023-04-03  178586  181735  176323  177111  1202359  0.003905
 2023-04-04  179669  185179  176619  178292  1476621  0.006668
 2023-04-05  178980  179964  175044  176225   762751 -0.011593
 2023-04-06  175733  175930  170321  173372   899061 -0.016190
 2023-04-07  173372  184687  171305  180555  1737556  0.041431
 ...            ...     ...     ...     ...      ...       ...
 2024-03-19  128000  128100  122200  125100   627338 -0.003981
 2024-03-20  123000  123800  119400  119700   757266 -0.043165
 2024-03-21  120300  121200  119500  120000   451396  0.002506
 2024-03-22  119200  121400  119100  120000   396268  0.000000
 2024-03-25  120500  122400  120300  121000   341937  0.008333

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  553000  558000  543000  555000   58113  0.003617
 2023-04-04  556000  561000  545000  548000   40836 -0.012613
 2023-04-05  547000  547000  529000  537000   80396 -0.020073
 2023-04-06  541000  541000  530000  531000   41532 -0.011173
 2023-04-07  531000  534000  526000  528000   47257 -0.005650
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  447500  452000  444000  448000   33604 -0.009945
 2024-03-20  451500  451500  437000  439500   48666 -0.018973
 2024-03-21  443500  446000  439500  441500   40778  0.004551
 2024-03-22  438000  443000  437500  440000   34873 -0.003398
 2024-03-25  452000  474000  452000  456000  132867  0.036364

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  374500  377500  370000  370500   58662 -0.002692
 2023-04-04  371500  386000  371500  385500  110313  0.040486
 2023-04-05  384500  388000  381000  381000   83629 -0.011673
 2023-04-06  378000  385000  377000  378500   84115 -0.006562
 2023-04-07  378500  382000  370000  370000  112951 -0.022457
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  191800  191800  187500  188300  131659 -0.022833
 2024-03-20  189700  194400  188700  191400  100130  0.016463
 2024-03-21  192800  194000  189800  191700   84260  0.001567
 2024-03-22  191100  192200  189000  191400   62228 -0.001565
 2024-03-25  191000  192800  189400  191800   67823  0.002090

 [240 rows x 6 columns],
              Open   High    Low  Close    Volume    Change
 Date
 2023-04-03  17020  17290  16810  17060   5999794  0.003529
 2023-04-04  17020  17480  17020  17280   5979172  0.012896
 2023-04-05  17080  17220  16610  16980   6849792 -0.017361
 2023-04-06  16950  17350  16900  17050   5869627  0.004122
 2023-04-07  17130  17150  16800  16830   4015924 -0.012903
 ...           ...    ...    ...    ...       ...       ...
 2024-03-19  18350  18920  17780  17840  12722844 -0.001120
 2024-03-20  17500  17750  17210  17740   6722040 -0.005605
 2024-03-21  17650  18130  17610  18070   5160145  0.018602
 2024-03-22  17890  18190  17790  17890   3747422 -0.009961
 2024-03-25  17890  17980  17230  17300   4860054 -0.032979

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  153600  155400  152100  155300  391930  0.017027
 2023-04-04  155000  155200  150700  151300  528311 -0.025757
 2023-04-05  151400  158000  150900  157800  819035  0.042961
 2023-04-06  157000  157000  152100  152400  504034 -0.034221
 2023-04-07  153700  155100  152800  153900  339439  0.009843
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  145500  149500  144100  147500  592794  0.015840
 2024-03-20  149700  150600  146800  147600  398918  0.000678
 2024-03-21  150100  150800  148100  149600  406093  0.013550
 2024-03-22  148200  149500  143300  144900  599778 -0.031417
 2024-03-25  145200  146200  144100  145000  223285  0.000690

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  117100  118800  116500  117000  275375  0.008621
 2023-04-04  117400  117900  116500  117600  159557  0.005128
 2023-04-05  117200  118300  117000  117700  148432  0.000850
 2023-04-06  117700  117700  115700  115700  178468 -0.016992
 2023-04-07  116000  116600  115300  116100  117978  0.003457
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  156700  161500  156500  158000  130764  0.006369
 2024-03-20  159600  163000  157000  158500  128564  0.003165
 2024-03-21  160200  160700  155300  158200  200943 -0.001893
 2024-03-22  156800  160400  156800  158100   95535 -0.000632
 2024-03-25  158200  158300  154700  155400  116681 -0.017078

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  23150  23350  23100  23150   871385 -0.002155
 2023-04-04  23100  23350  23100  23150   753418  0.000000
 2023-04-05  23150  23300  23000  23000   827598 -0.006479
 2023-04-06  22950  23000  22700  22800   799121 -0.008696
 2023-04-07  22750  22950  22650  22750   761073 -0.002193
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  21750  21800  21250  21350  1249970 -0.020642
 2024-03-20  21450  21650  21400  21400   573629  0.002342
 2024-03-21  21550  21800  21550  21750   696110  0.016355
 2024-03-22  21750  22100  21750  21800   761816  0.002299
 2024-03-25  21800  21950  21800  21800   355730  0.000000

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  182300  185900  181700  182800  152348 -0.003815
 2023-04-04  183000  189500  182800  189400  218430  0.036105
 2023-04-05  189400  189600  184200  184200  142008 -0.027455
 2023-04-06  183000  185300  182300  182600  114465 -0.008686
 2023-04-07  182700  185900  180600  183500  112304  0.004929
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  234500  243000  234000  237000  114517 -0.004202
 2024-03-20  241000  243000  234000  237500   72127  0.002110
 2024-03-21  239000  241000  234500  240500   81387  0.012632
 2024-03-22  237500  240000  232500  236000   64214 -0.018711
 2024-03-25  236000  242500  232500  240000  125503  0.016949

 [240 rows x 6 columns],
              Open   High    Low  Close   Volume    Change
 Date
 2023-04-03  53600  53600  50100  50500  4641724 -0.059590
 2023-04-04  51800  52000  50100  50400  3003343 -0.001980
 2023-04-05  50300  50800  48800  48950  2688586 -0.028770
 2023-04-06  48700  51200  47450  49750  5151937  0.016343
 2023-04-07  51000  51700  50100  50900  2976570  0.023116
 ...           ...    ...    ...    ...      ...       ...
 2024-03-19  27650  27700  27050  27050   545394 -0.021700
 2024-03-20  27300  27550  27000  27050   452820  0.000000
 2024-03-21  27550  28100  27350  27550   881630  0.018484
 2024-03-22  27600  28050  27500  27600   784096  0.001815
 2024-03-25  27600  27600  27150  27250   580568 -0.012681

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  136700  138800  135600  136400  149594 -0.002924
 2023-04-04  136400  138300  135100  137700  213636  0.009531
 2023-04-05  137700  140400  135500  135900  259057 -0.013072
 2023-04-06  136200  136400  133700  134500  125428 -0.010302
 2023-04-07  134100  137200  133000  136300  138699  0.013383
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  111800  112800  110400  111700  103703 -0.010629
 2024-03-20  112800  115200  112300  113200  159484  0.013429
 2024-03-21  113600  114800  113400  114300  128058  0.009717
 2024-03-22  113900  120400  113400  116100  455456  0.015748
 2024-03-25  116800  120400  116100  118100  223691  0.017227

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  55400  56300  55000  55700  239122  0.001799
 2023-04-04  55700  56700  55200  56300  255310  0.010772
 2023-04-05  56200  56700  55600  56200  239333 -0.001776
 2023-04-06  55900  56100  54200  54400  336276 -0.032028
 2023-04-07  54500  56000  53800  55600  254472  0.022059
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  39350  39600  38350  38500  347840 -0.029004
 2024-03-20  38900  39050  38050  38500  261696  0.000000
 2024-03-21  39250  39800  39100  39500  287646  0.025974
 2024-03-22  39150  39850  39000  39400  180060 -0.002532
 2024-03-25  39400  39450  38800  39250  124420 -0.003807

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  188000  189500  183700  184000  141199 -0.025940
 2023-04-04  184900  190900  184500  190300  191538  0.034239
 2023-04-05  190200  191300  188200  190700  114403  0.002102
 2023-04-06  190300  212500  190300  205000  862698  0.074987
 2023-04-07  206000  219000  200500  217000  493700  0.058537
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  197300  197300  191200  192700  190105 -0.023810
 2024-03-20  193400  195900  191300  193300  105360  0.003114
 2024-03-21  195200  199200  194500  195200  182750  0.009829
 2024-03-22  194000  196600  192000  195800  162868  0.003074
 2024-03-25  195800  208500  195800  207000  367548  0.057201

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  159700  160200  157600  157700   90593 -0.005047
 2023-04-04  157700  159500  157700  159400   75294  0.010780
 2023-04-05  159300  160700  158800  160000   73897  0.003764
 2023-04-06  160100  160100  157400  157400   68079 -0.016250
 2023-04-07  157600  157800  156100  156600   51316 -0.005083
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  185300  191300  185000  185000   67159 -0.006445
 2024-03-20  186800  188500  184600  185200   50027  0.001081
 2024-03-21  186600  187100  182600  186700   78897  0.008099
 2024-03-22  186000  188100  184300  187400   80123  0.003749
 2024-03-25  187200  187300  182000  182300  106034 -0.027215

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  192000  193000  185500  186100  115856 -0.024633
 2023-04-04  186300  188600  184500  185700   75074 -0.002149
 2023-04-05  185900  187500  183500  184300   66151 -0.007539
 2023-04-06  182500  184400  181600  182500   69119 -0.009767
 2023-04-07  182500  183700  180800  182900   71986  0.002192
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  120200  120700  117500  118500  151766 -0.014143
 2024-03-20  118400  118700  116800  117000  158334 -0.012658
 2024-03-21  118200  119300  117400  118800  175263  0.015385
 2024-03-22  118600  122200  118400  121000  137340  0.018519
 2024-03-25  121700  121700  119100  120200   98896 -0.006612

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  273000  273000  267000  271500  215759  0.003697
 2023-04-04  272000  272000  264000  265000  173038 -0.023941
 2023-04-05  264500  269000  264500  267000  126828  0.007547
 2023-04-06  265000  267000  254000  255000  306612 -0.044944
 2023-04-07  257000  258000  253500  255500  259746  0.001961
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19  190900  191400  188400  189700  120051 -0.003153
 2024-03-20  191200  193100  189800  192300  139146  0.013706
 2024-03-21  193800  194300  191400  193900  142744  0.008320
 2024-03-22  190800  193500  189900  192400  136236 -0.007736
 2024-03-25  192700  195500  190800  191300  116268 -0.005717

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  65600  66300  64400  65600  199516 -0.010558
 2023-04-04  65700  70200  65400  69800  453137  0.064024
 2023-04-05  69800  70500  69000  69600  225828 -0.002865
 2023-04-06  70000  72500  69400  70300  366444  0.010057
 2023-04-07  70600  72700  69900  72100  246914  0.025605
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  59500  59700  56800  57500  100683 -0.046434
 2024-03-20  57900  58800  57100  57300   47665 -0.003478
 2024-03-21  57800  59200  57800  59000   71609  0.029668
 2024-03-22  58300  59500  58100  58700   54338 -0.005085
 2024-03-25  59500  64300  58800  62700  195842  0.068143

 [240 rows x 6 columns],
               Open    High     Low   Close  Volume    Change
 Date
 2023-04-03  135100  138900  135000  137800   66429  0.008785
 2023-04-04  138500  141500  136900  140400   84478  0.018868
 2023-04-05  142000  142300  138200  138500   54913 -0.013533
 2023-04-06  138000  140900  137300  137500   68846 -0.007220
 2023-04-07  137600  138800  135300  136200   71461 -0.009455
 ...            ...     ...     ...     ...     ...       ...
 2024-03-19   94300   95500   91500   92000  243232 -0.022317
 2024-03-20   92500   93300   90800   91000  273294 -0.010870
 2024-03-21   91600   91700   90100   91200  286234  0.002198
 2024-03-22   90800   92300   90600   90800  235976 -0.004386
 2024-03-25   91000   91100   90000   90500  201489 -0.003304

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date
 2023-04-03  20100  20400  19980  20000  884485  0.005025
 2023-04-04  20150  20150  19730  19980  628705 -0.001000
 2023-04-05  19980  20050  19880  19930  572501 -0.002503
 2023-04-06  19900  20050  19750  19770  644359 -0.008028
 2023-04-07  19850  19850  19620  19730  531808 -0.002023
 ...           ...    ...    ...    ...     ...       ...
 2024-03-19  16890  17040  16650  16650  530750 -0.019435
 2024-03-20  16800  16900  16670  16710  375033  0.003604
 2024-03-21  16860  16970  16670  16770  461966  0.003591
 2024-03-22  16700  16860  16680  16830  372123  0.003578
 2024-03-25  16810  16900  16750  16810  369810 -0.001188

 [240 rows x 6 columns],
              Open   High    Low  Close  Volume    Change
 Date

In [15]:
for i in code.index :
    sell[i]['종목코드'] = code.loc[i, '종목코드']
    sell[i]['종목명'] = code.loc[i, '종목명']

In [24]:
sell_data = pd.concat(sell)
sell_data['sell_rtn'] = sell_data.groupby(['종목코드']).Close.pct_change()

sell_data

,Open,High,Low,Close,Volume,Change,종목코드,종목명,sell_rtn
Date,,,,,,,,,
2023-04-03,3495,3515,3460,3515,85518,0.008608,400760,NH올원리츠,NaN
2023-04-04,3525,3555,3505,3555,83509,0.011380,400760,NH올원리츠,0.011380
2023-04-05,3555,3560,3445,3490,228903,-0.018284,400760,NH올원리츠,-0.018284
2023-04-06,3490,3490,3390,3430,227726,-0.017192,400760,NH올원리츠,-0.017192
2023-04-07,3430,3430,3370,3375,193698,-0.016035,400760,NH올원리츠,-0.016035
...,...,...,...,...,...,...,...,...,...
2024-03-19,1465,1529,1440,1482,5463523,0.017159,452260,한화갤러리아,0.017159
2024-03-20,1482,1549,1478,1507,4370477,0.016869,452260,한화갤러리아,0.016869
2024-03-21,1519,1535,1493,1493,2142983,-0.009290,452260,한화갤러리아,-0.009290
2024-03-22,1500,1514,1486,1486,1180297,-0.004689,452260,한화갤러리아,-0.004689
2024-03-25,1487,1522,1473,1505,2302019,0.012786,452260,한화갤러리아,0.012786

In [25]:
sell_data = sell_data.drop(columns=['Open','High','Low','Volume','Change','종목코드'])
sell_data['Date'] = sell_data.index

sell_data

            Close     종목명  sell_rtn       Date
Date
2023-04-03   3515  NH올원리츠       NaN 2023-04-03
2023-04-04   3555  NH올원리츠  0.011380 2023-04-04
2023-04-05   3490  NH올원리츠 -0.018284 2023-04-05
2023-04-06   3430  NH올원리츠 -0.017192 2023-04-06
2023-04-07   3375  NH올원리츠 -0.016035 2023-04-07
...           ...     ...       ...        ...
2024-03-19   1482  한화갤러리아  0.017159 2024-03-19
2024-03-20   1507  한화갤러리아  0.016869 2024-03-20
2024-03-21   1493  한화갤러리아 -0.009290 2024-03-21
2024-03-22   1486  한화갤러리아 -0.004689 2024-03-22
2024-03-25   1505  한화갤러리아  0.012786 2024-03-25

[222960 rows x 4 columns]

In [27]:
BL_pbr = manufacture.loc[(manufacture['기업구분'] == 'B') & (manufacture['1/PBR'] == 'L')]
BH_pbr = manufacture.loc[(manufacture['기업구분'] == 'B') & (manufacture['1/PBR'] == 'H')]
SL_pbr = manufacture.loc[(manufacture['기업구분'] == 'S') & (manufacture['1/PBR'] == 'L')]
SH_pbr = manufacture.loc[(manufacture['기업구분'] == 'S') & (manufacture['1/PBR'] == 'H')]

In [28]:
BL_pbr_rtn = pd.merge(BL_pbr, sell_data, on='종목명')
BL_pbr_rtn.dropna(axis=0, inplace=True)

BH_pbr_rtn = pd.merge(BH_pbr, sell_data, on='종목명')
BH_pbr_rtn.dropna(axis=0, inplace=True)

SL_pbr_rtn = pd.merge(SL_pbr, sell_data, on='종목명')
SL_pbr_rtn.dropna(axis=0, inplace=True)

SH_pbr_rtn = pd.merge(SH_pbr, sell_data, on='종목명')
SH_pbr_rtn.dropna(axis=0, inplace=True)

In [29]:
BL_pbr_rtn

,Unnamed: 0,종목코드,종목명,시가총액,기업구분,PBR,1/PBR,Close,sell_rtn,Date
1,0,5930,삼성전자,3.301290e+14,B,1.27,L,63600,0.007924,2023-04-04
2,0,5930,삼성전자,3.301290e+14,B,1.27,L,63900,0.004717,2023-04-05
3,0,5930,삼성전자,3.301290e+14,B,1.27,L,62300,-0.025039,2023-04-06
4,0,5930,삼성전자,3.301290e+14,B,1.27,L,65000,0.043339,2023-04-07
5,0,5930,삼성전자,3.301290e+14,B,1.27,L,65700,0.010769,2023-04-10
...,...,...,...,...,...,...,...,...,...,...
7675,44,112610,씨에스윈드,2.901390e+12,B,3.24,L,50800,-0.009747,2024-03-19
7676,44,112610,씨에스윈드,2.901390e+12,B,3.24,L,52000,0.023622,2024-03-20
7677,44,112610,씨에스윈드,2.901390e+12,B,3.24,L,52000,0.000000,2024-03-21
7678,44,112610,씨에스윈드,2.901390e+12,B,3.24,L,51400,-0.011538,2024-03-22
7679,44,112610,씨에스윈드,2.901390e+12,B,3.24,L,50900,-0.009728,2024-03-25

In [31]:
import numpy as np

# def weighted_average(group, avg_name, weight_name):
def weighted_average(group, avg_name, _name):
    d = group[avg_name]
    # w = group[weight_name]
    w = group[_name]
    try:
        # return (d * w).sum() / w.sum()
        return d.sum() / w.nunique()
    except ZeroDivisionError:
        return np.nan

In [32]:
BH_pbr_avgRtn = BH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BH_pbr_avg'})
BL_pbr_avgRtn = BL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BL_pbr_avg'})
SH_pbr_avgRtn = SH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SH_pbr_avg'})
SL_pbr_avgRtn = SL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SL_pbr_avg'})

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_84128/3404557599.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  BH_pbr_avgRtn = BH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BH_pbr_avg'})
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_84128/3404557599.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  BL_pbr_avgRtn = BL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'BL_pbr_avg'})
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_84128/3404557599.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  SH_pbr_avgRtn = SH_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SH_pbr_avg'})
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_84128/3404557599.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  SL_pbr_avgRtn = SL_pbr_rtn.groupby(['Date']).apply(weighted_average, 'sell_rtn', '종목명').to_frame().reset_index().rename(columns={0:'SL_pbr_avg'})

In [33]:
from functools import reduce

pbr_avgRtn_list = [BH_pbr_avgRtn, BL_pbr_avgRtn, SH_pbr_avgRtn, SL_pbr_avgRtn]
df_merge = reduce(lambda left, right: pd.merge(left, right, on='Date'), pbr_avgRtn_list)
# pd.merge([BH_pbr_avgRtn, BL_pbr_avgRtn, SH_pbr_avgRtn, SL_pbr_avgRtn], on='Date',axis=1)
df_merge

          Date  BH_pbr_avg  BL_pbr_avg  SH_pbr_avg  SL_pbr_avg
0   2023-04-04    0.006634    0.015729    0.010173    0.009385
1   2023-04-05   -0.002874    0.005084   -0.000961    0.004973
2   2023-04-06   -0.009685   -0.008185   -0.008797   -0.006539
3   2023-04-07   -0.000917    0.000808    0.000233    0.002926
4   2023-04-10    0.004760    0.004393   -0.006439   -0.003749
..         ...         ...         ...         ...         ...
234 2024-03-19   -0.026583   -0.009621   -0.003006   -0.003027
235 2024-03-20    0.003264    0.007288    0.003992    0.008088
236 2024-03-21    0.019513    0.010174    0.008600    0.007848
237 2024-03-22   -0.004787    0.003787    0.002175    0.005545
238 2024-03-25   -0.008217    0.001042   -0.001873   -0.000865

[239 rows x 5 columns]

In [51]:
smb = []
hml = []
for i in df_merge.index :
    SMB = ((df_merge.loc[i]['SH_pbr_avg']) + (df_merge.loc[i]['SL_pbr_avg'])) - ((df_merge.loc[i]['BH_pbr_avg']) + (df_merge.loc[i]['BL_pbr_avg'])) / 2
    smb.append(SMB)
    HML = ((df_merge.loc[i]['SH_pbr_avg']) + (df_merge.loc[i]['BH_pbr_avg'])) - ((df_merge.loc[i]['SL_pbr_avg']) + (df_merge.loc[i]['BL_pbr_avg'])) / 2
    hml.append(HML)

df_merge['SMB'] = smb
df_merge['HML'] = hml

df_merge

,Date,BH_pbr_avg,BL_pbr_avg,SH_pbr_avg,SL_pbr_avg,SMB,HML
0,2023-04-04,0.006634,0.015729,0.010173,0.009385,0.008377,0.004250
1,2023-04-05,-0.002874,0.005084,-0.000961,0.004973,0.002907,-0.008864
2,2023-04-06,-0.009685,-0.008185,-0.008797,-0.006539,-0.006401,-0.011121
3,2023-04-07,-0.000917,0.000808,0.000233,0.002926,0.003213,-0.002551
4,2023-04-10,0.004760,0.004393,-0.006439,-0.003749,-0.014764,-0.002001
...,...,...,...,...,...,...,...
234,2024-03-19,-0.026583,-0.009621,-0.003006,-0.003027,0.012069,-0.023266
235,2024-03-20,0.003264,0.007288,0.003992,0.008088,0.006804,-0.000433
236,2024-03-21,0.019513,0.010174,0.008600,0.007848,0.001604,0.019102
237,2024-03-22,-0.004787,0.003787,0.002175,0.005545,0.008221,-0.007278
238,2024-03-25,-0.008217,0.001042,-0.001873,-0.000865,0.000850,-0.010178